### ISSUE TITLE
Modulo criação de atuação

### ISSUE THREAD

**Issue by felansu** [gustavobte/fisgo#2]
Na **tela principal** deverá ter um botão para incluir uma **nova atuação**.

Quando pulsar no botão deverá mostrar uma **nova tela com 2 botões**:

**1.** Incluir Doc NF
**2.** Incluir veiculo

Também **deverá mostrar uma tabela contendo a lista de items**  incluídos para verificação contendo 3 colunas:

* Tipo: Veiculo / NF
* Identificação
* Status: Com ou sem incidências 

Quando incluir algum documento **NF ou placa de veiculo** deverá realizar a verificação. A funcionalidade encontra-se na issue #3.

- [x] Nova atuação
- [x] Incluir DOC NF
- [x] Incluir veiculo
- [x] Lista de items incluídos [tipo, identificação e status]
- [x] Funcionalidade para remover item incluído
- [x] Não habilitar botão incluir até ter o input preenchido

**Comment by gustavobte** [comment]
Front Ok!
